fix: explicit bundle path for artifact upload and bump version 1.0.2

diff --git a/.github/workflows/build-tauri-agent.yml b/.github/workflows/build-tauri-agent.yml
--- a/.github/workflows/build-tauri-agent.yml
+++ b/.github/workflows/build-tauri-agent.yml
@@ -32,9 +32,13 @@ jobs:
         working-directory: ./hardware_agent
         run: npm run tauri build
 
+      - name: Debug Output Path
+        working-directory: ./hardware_agent
+        run: dir src-tauri\target\release\bundle\nsis /s /b || echo "Directory not found!"
+
       - name: Upload Artifact
         uses: actions/upload-artifact@v4
         with:
           compression-level: 0
           name: MKT_Hardware_Agent_Installer
-          path: hardware_agent/src-tauri/target/**/bundle/nsis/*.exe
+          path: hardware_agent/src-tauri/target/release/bundle/nsis/*.exe
